### ISSUE TITLE
error with the new support library tations:23.2.0

### ISSUE THREAD

**Issue by Spiderbezno** [javiersantos/MaterialStyledDialogs#10]
com.github.afollestad.material-dialogs/core/0.8.5.4/res/values-v11/values-v11.xml/Users/Jorge1Old/AndroidStudioProjects/My_Andorra_Telecom/app/build/intermediates/exploded-aar/com.github.afollestad.material-dialogs/core/0.8.5.4/res/values-v11/values-v11.xml

Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

**Comment by Aeefire** [comment]
I have the same issue.

**Comment by javiersantos** [comment]
Could you try the latest snapshot release of the library?
```Javascript
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:-SNAPSHOT'
}
```

**Comment by Spiderbezno** [comment]
Tomorrow I will try, now I've just leave the work
Could you try the latest snapshot release of the library?
```Javascript
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:-SNAPSHOT'
}
```

---

**Comment by Aeefire** [comment]
Worked for me.

**Comment by F4bioo** [comment]
it's working

**Comment by javiersantos** [comment]
Nice! Thank you guys :+1:

**Comment by Luckyrana001** [comment]
Thanks all, it work for me too
