### ISSUE TITLE
Failed to resolve: com.github.javiersantos:MaterialStyledDialogs:1.2.1

### ISSUE THREAD

**Issue by davidbeloo** [javiersantos/MaterialStyledDialogs#11]
Hi,

Adding this line 
`compile 'com.github.javiersantos:MaterialStyledDialogs:1.2.1'`
to gradle file, results 

> Failed to resolve: com.github.javiersantos:MaterialStyledDialogs:1.2.1

**Comment by javiersantos** [comment]
I'm not able to reproduce the issue. Please make sure that you have added the Jitpack repository to your project build.gradle.

```Javascript
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by davidbeloo** [comment]
Sorry my bad.

**Comment by javiersantos** [comment]
Similar issue: #18
