### ISSUE TITLE
failed to resolve .... while updating from 1.3 to 1.4

### ISSUE THREAD

**Issue by arashifunsho** [javiersantos/MaterialStyledDialogs#18]
The library works fine until i changed 1.3 to 1.4 in below line in gradle:

compile 'com.github.javiersantos:MaterialStyledDialogs:1.4'

error failed to resolve ..... is what i get. But when i change back to 1.3, it works fine. 

jitpack.io has already been added to maven. Please help asap

**Comment by Sleeper9** [comment]
Hi, I had no problems with the upgrade. Does this still not work? Maybe you can copy your build.gradles here.

**Comment by javiersantos** [comment]
I'm not able to reproduce the issue. Could you try using the latest version (v1.4.1)?

Thank you.

**Comment by arashifunsho** [comment]
i am able to use the new version 1.4 on a new project. But i could not update from 1.3 to 1.4 on an old project. Maybe it is something I am not doing.
