### ISSUE TITLE
How can I customize open and close animation of the dialog

### ISSUE THREAD

**Issue by maddog05** [javiersantos/MaterialStyledDialogs#2]
How can I change or set my custom animation for the open/close animation of the dialog.

**Comment by javiersantos** [comment]
It is not possible, because dialog animations are set in the `style.xml` file and it can not be changed programmatically.

However, I can add more animations to the dialogs. Let me know which animations do you want to see in upcoming updates.

**Comment by maddog05** [comment]
maybe the duration of the animation (FAST = 300ms, NORMAL = 600ms, SLOW = 1000ms)
basically that

**Comment by javiersantos** [comment]
Using the latest library version.

```Java
// Set if the dialog will be displayed with an open and close animation, with custom duration.
// Default: false, Duration.NORMAL
.withDialogAnimation(true, Duration.SLOW)
```

**Comment by maddog05** [comment]
Thanks, sorry for answer you late
