### ISSUE TITLE
Make Header With Title and Drawable overlay optional

### ISSUE THREAD

**Issue by willrichman** [javiersantos/MaterialStyledDialogs#22]
As of now, if I want to have a header with a title (`HEADER_WITH_TITLE`), as well as a `headerDrawable`, the dialog builder adds a gray overlay of a color filter over that drawable:

```java
if (this.style == Style.HEADER_WITH_TITLE) {
    dialogHeader.setColorFilter(Color.rgb(123, 123, 123), Mode.MULTIPLY);
}
```

I have a background drawable that is already dark enough for text to be visible over it, and as such, would not need this filter to be added. It makes my header appear much darker than it should. Can we add a method to turn off this header filter?

**Comment by javiersantos** [comment]
Checkout the latest update.

```Java
new MaterialStyledDialog(this)
	.setTitle("Awesome!")
	.setDescription("What can we improve? Your feedback is always welcome.")
	.setHeaderDrawable(R.drawable.header)
	.withDarkerOverlay(true)
	.show();
```

https://github.com/javiersantos/MaterialStyledDialogs/blob/master/README.md#adding-a-darkergrey-overlay-to-the-header-background

**Comment by willrichman** [comment]
Looks fantastic, thanks!
