### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by rahulupadhyay** [javiersantos/MaterialStyledDialogs#28]
In description when text size is small then its automatically right aligned. So how to make it left align? 
![device-2016-08-12-165142](https://cloud.githubusercontent.com/assets/1897585/17620940/96fa0b4a-60ad-11e6-9886-46db49a7e099.png)

Please check this image and provide a solution for that.

**Comment by javiersantos** [comment]
I think that the `layout_gravity` is wrong in both styles and it aligns the description to the right.

https://github.com/javiersantos/MaterialStyledDialogs/blob/master/library/src/main/res/layout/style_dialog_header_icon.xml#L47
https://github.com/javiersantos/MaterialStyledDialogs/blob/master/library/src/main/res/layout/style_dialog_header_title.xml#L40

**Comment by rahulupadhyay** [comment]
@javiersantos , so which steps I need to take in my app?

**Comment by javiersantos** [comment]
I've released a new update, just [grab the latest version](https://github.com/javiersantos/MaterialStyledDialogs#how-to-include).

**Comment by rahulupadhyay** [comment]
thanks @javiersantos
