### ISSUE TITLE
Can we use this library without icon ( imageView )

### ISSUE THREAD

**Issue by anvesh523** [javiersantos/MaterialStyledDialogs#3]
I want material dialog only for text & action buttons like
![Image](https://cloud.githubusercontent.com/assets/10726276/12972550/3a12c5c8-d0cc-11e5-9ea6-6129d0bad7a3.png)
In your library if is there any option with hide the imageView, it will be cool...

**Comment by javiersantos** [comment]
If I understand correctly you want to hide the ImageView but showing the header background (plain color or drawable). Am I right?

**Comment by anvesh523** [comment]
Might be no, I want to hide complete header ( plain color ) if I am not using any icon. Only Title description and action buttons...

**Comment by javiersantos** [comment]
Oh, I see... It's not possible at the moment, but I think you should use the [material-dialogs](https://github.com/afollestad/material-dialogs) library instead. That library will do exactly what you want.

BTW, this library is based on the other one that I mentioned before.

**Comment by anvesh523** [comment]
Thank you for quick reply and sharing the information. @javiersantos
