### ISSUE TITLE
setIcon(...) with vector drawables crashes the app

### ISSUE THREAD

**Issue by krupalshah** [javiersantos/MaterialStyledDialogs#33]
Using vector drawable with `setIcon(...`) crashes the app on older devices than the lollipop. Looks like library needs to use `AppCompatImageView`with`app:srcCompat` attribute now instead of older `ImageView`with `android:src`.

**Comment by Albiwalbi** [comment]
Hi,

I just ran into the same issue. Why wasn't this fixed? For animations it's better to use vectors.

Thanks in advance,
AJP
