### ISSUE TITLE
items list

### ISSUE THREAD

**Issue by kashifandroiddev** [javiersantos/MaterialStyledDialogs#4]
how can i add list of items 

like string list 

thanks

**Comment by javiersantos** [comment]
Seems that the base library doesn't allow to add items when using a custom view: https://github.com/afollestad/material-dialogs/blob/master/core%2Fsrc%2Fmain%2Fjava%2Fcom%2Fafollestad%2Fmaterialdialogs%2FMaterialDialog.java#L740

I will think for another workaround, but looks that it's not going to be available soon.

**Comment by javiersantos** [comment]
The latest update includes support for custom views. This means that you will be able to create a ListView / RecyclerView with your own list of items.

See the documentation: https://github.com/javiersantos/MaterialStyledDialogs/wiki/Adding-a-custom-view
