### ISSUE TITLE
FATAL EXCEPTION: main java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by A2DNEW** [javiersantos/MaterialStyledDialogs#48]
Hi
After add to gradle this code, get error :
compile 'com.github.javiersantos:MaterialStyledDialogs:2.1'

FATAL EXCEPTION: main java.lang.RuntimeException: Unable to start activity ComponentInfo

**Comment by javiersantos** [comment]
Please provide your entire Logcat stack trace.
