### ISSUE TITLE
[Improvement] If length of the description reached specified length, make the TextView scrollable

### ISSUE THREAD

**Issue by alirezaaa** [javiersantos/MaterialStyledDialogs#6]
Hi,

I tried to provide smaller description but it still is long for a smartphone and make the appearance of the dialog bad. The best solution is providing scrollable `TextView`.

**Comment by javiersantos** [comment]
Thanks.
```Javascript
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:1.2'
}
```
