### ISSUE TITLE
failed to resolve even after adding Jitpack, 

### ISSUE THREAD

**Issue by MHaris404** [javiersantos/MaterialStyledDialogs#79]
- [*] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [*] I have verified that I am using the latest version of MaterialStyledDialogs.
- [*] I have given my issue a non-generic title.
- [ ] I have read over the [README](https://github.com/javiersantos/MaterialStyledDialogs/blob/master/README.md) and [Wiki](https://github.com/javiersantos/MaterialStyledDialogs/wiki) (before asking questions on how to do something).

###### Details
 - MaterialStyledDialogs version: `2.1`
 - Device OS version: `9...`
 - Device Manufacturer: `Samsung`
 - Device Name: `Samsung A20`

###### Reproduction Steps

1.
2.
3.

**Comment by javiersantos** [comment]
Make sure you are adding the Jitpack repository in the project build.gradle file, not the module one.

Example: https://github.com/javiersantos/MaterialStyledDialogs/blob/master/build.gradle#L16
