### ISSUE TITLE
I cant clone project

### ISSUE THREAD

**Issue by tellfa** [javiersantos/MaterialStyledDialogs#8]
Hi, when clone this project in Android Studio 1.5.1 show me this error : 
![8](https://cloud.githubusercontent.com/assets/10583945/13148544/0da7d9ae-d673-11e5-8480-20cf5973920f.PNG)
My SDK version : 23.1.1 (lasted). how to fix it?

**Comment by javiersantos** [comment]
Please, make sure you have included the `jcenter()` repository in your project **build.gradle** too.
```Javascript
repositories {
    jcenter()
    maven {
        url "https://jitpack.io"
    }
}
```

Does it solve your issue?

**Comment by tellfa** [comment]
please see this : 
![9](https://cloud.githubusercontent.com/assets/10583945/13149077/45ba4b4a-d675-11e5-9b24-7ca8b538a837.PNG)

**Comment by tellfa** [comment]
how to fix it my dear friend?

**Comment by tellfa** [comment]
how to fix it my dear friend?

**Comment by javiersantos** [comment]
Be sure that `jcenter()` is included before the maven repository.
<img width="353" alt="screen shot 2016-02-19 at 10 38 17" src="https://cloud.githubusercontent.com/assets/2229658/13171786/f6477cba-d6f4-11e5-8b42-d906877d7125.png">

**Comment by tellfa** [comment]
Why shoe me this error? :( I need this library
![10](https://cloud.githubusercontent.com/assets/10583945/13173829/f73b4294-d714-11e5-8385-d33ed236317f.PNG)

**Comment by javiersantos** [comment]
Could you manually add this library in your dependencies and see if it works?

compile 'me.zhanghai.android.materialprogressbar:library:1.1.4'

**Comment by tellfa** [comment]
When added this library show me this error : 
![11](https://cloud.githubusercontent.com/assets/10583945/13174869/c7eaea24-d71b-11e5-99e8-376e63dd6429.PNG)

**Comment by javiersantos** [comment]
Have you synced with Gradle your project after doing the changes?
<img width="197" alt="screen shot 2016-02-19 at 12 48 40" src="https://cloud.githubusercontent.com/assets/2229658/13174923/2a028dbc-d707-11e5-997d-0f6c07b5cd48.png">

**Comment by tellfa** [comment]
yes, sync my project and show this error

**Comment by deletescape** [comment]
Is your Computer connected to the internet? (Sorry bout that stupid question but if not it will not work)

**Comment by dtheodor79** [comment]
Hello, I have the exact same issue. I have added the maven repository as you describe, however it Android Studio 1.5.1 complains:

Error:(104, 13) Failed to resolve: com.github.javiersantos:MaterialStyledDialogs:1.2.1

Note, that the other library you mentioned ( me.zhanghai.android.materialprogressbar:library:1.1.4 ) is added successfully.

Any way to resolve it? Thanks!

**Comment by deletescape** [comment]
Ok guys I will take a look at it for you two!

**Comment by dtheodor79** [comment]
Thanks, cause the library looks very nice! ;)

**Comment by javiersantos** [comment]
Guys, could you use this Gradle dependency instead of the current one and check if it works? Thanks!

```Javascript
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:1.2.2@aar'
}
``` 
or
```Javascript
dependencies {
    compile('com.github.javiersantos:MaterialStyledDialogs:1.2.2@aar'){ transitive = true }
}
```

**Comment by dtheodor79** [comment]
Just tried both cases, and still shows the same error :(

**Comment by tellfa** [comment]
Show me error again :disappointed:

**Comment by aakash94** [comment]
I had the exact same error, it is because of pasting the code in the wrong place in the project's build.gradel , I am uploading an image to clarify this.. 

` maven {
        url "https://jitpack.io"
    }` 
must be in the allprojects and not in buildscripts
this is my code that works perfectly for me.

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}`

![debug](https://cloud.githubusercontent.com/assets/6615458/13712735/50a741b6-e7eb-11e5-8d9f-59fc0d81de09.jpg)

**Comment by javiersantos** [comment]
Thank you for clarifying, @aakash94!

**Comment by tellfa** [comment]
show me error  again @aakash94

**Comment by vish30** [comment]
Thank you so much @aakash94 this solved the error for other jitpack.io repositories too.
