### ISSUE TITLE
I have 3 layout with different 3 color in dialog.

### ISSUE THREAD

**Issue by PeterPhyo** [javiersantos/MaterialStyledDialogs#9]
I would like to use 2 colors (HeaderColor = primary color & [Text , Button] = white color). 

new MaterialStyledDialog(CargoPlaceActivity.this)
                                        // .setTitle("Logout!")
                                        .setDescription("Are you sure, you want to logout ?")
                                        .setIcon(R.drawable.splash)
                                        .withDialogAnimation(true, Duration.SLOW)
                                        .setCancelable(false)
                                        .setPositive(getResources().getString(R.string.positive_button), new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(MaterialDialog dialog, DialogAction which) {
                                               //
                                            }
                                        })
                                        .setNegative(getResources().getString(R.string.negative_button), new MaterialDialog.SingleButtonCallback() {
                                            @Override
                                            public void onClick(MaterialDialog dialog, DialogAction which) {
                                                //
                                            }
                                        })
                                        .show();

![2016-02-23_15 16 37 2](https://cloud.githubusercontent.com/assets/16751250/13246278/0b422ce2-da41-11e5-9305-b1f87478b379.png)

**Comment by PeterPhyo** [comment]
What can be the problem? Help Me.

**Comment by NicoChacha** [comment]
Hi, I have the same issue. The "button layout" background is dark. Any idea to fix it ? I tried to change the app Theme from light to dark => no effect. So frustrating ='(

**Comment by NicoChacha** [comment]
I found the problem.
It seems to be the : <item name="android:textColorPrimary">@android:color/white</item> line, into the style.xml file which cause the black layout color. If i remove the line or set the color to black, the layout is white.
Hoping this will help someone.

**Comment by javiersantos** [comment]
It should be fixed using the latest update. Thanks!

```gradle
dependencies {
    compile 'com.github.javiersantos:MaterialStyledDialogs:1.3.1'
}
```
